TYPE_EXPANSION_MAP = {
    # --- THIRD-PARTY HTTP & NETWORKING (OKIO, NING, UNIREST, APACHE, GOOGLE, ASYNC) ---
    "Buffer": "okio.Buffer",
    "BufferedSink": "okio.BufferedSink",
    "ByteString": "okio.ByteString",
    "Response": "org.asynchttpclient.Response",  # Mapping to most recent AsyncHttpClient
    "Response_Ning": "com.ning.http.client.Response",
    "HttpResponse": "com.google.api.client.http.HttpResponse",
    "HttpResponse_Mashape": "com.mashape.unirest.http.HttpResponse",
    "HttpRequest": "com.google.api.client.http.HttpRequest",
    "LowLevelHttpResponse": "com.google.api.client.http.LowLevelHttpResponse",
    "HttpMediaType": "com.google.api.client.http.HttpMediaType",
    "HttpPatch": "org.apache.http.client.methods.HttpPatch",
    "HttpRequestBase": "org.apache.http.client.methods.HttpRequestBase",
    "RequestLine": "org.apache.http.RequestLine",
    "io.netty.handler.codec.http.HttpHeaders": "io.netty.handler.codec.http.HttpHeaders",

    # --- ANDROID GRAPHICS, UI & WIDGETS ---
    "Bitmap": "android.graphics.Bitmap",
    "Bitmap$Config": "android.graphics.Bitmap$Config",
    "Canvas": "android.graphics.Canvas",
    "Paint": "android.graphics.Paint",
    "Color": "android.graphics.Color",
    "ColorSpace": "android.graphics.ColorSpace",
    "Point": "android.graphics.Point",
    "PointF": "android.graphics.PointF",
    "EditText": "android.widget.EditText",
    "Editable": "android.text.Editable",
    "TextView$BufferType": "android.widget.TextView$BufferType",
    "Rect": "android.graphics.Rect",
    "RectF": "android.graphics.RectF",

    # --- ANDROID SYSTEM, UTILS & OS ---
    "Parcel": "android.os.Parcel",
    "Parcelable": "android.os.Parcelable",
    "Bundle": "android.os.Bundle",
    "IBinder": "android.os.IBinder",
    "PersistableBundle": "android.os.PersistableBundle",
    "ClipData": "android.content.ClipData",
    "ComponentName": "android.content.ComponentName",
    "Context": "android.content.Context",
    "ContentValues": "android.content.ContentValues",
    "ContentResolver": "android.content.ContentResolver",
    "ContentProvider": "android.content.ContentProvider",
    "Handler": "android.os.Handler",
    "Message": "android.os.Message",
    "Intent": "android.content.Intent",
    "IntentFilter": "android.content.IntentFilter",
    "IntentFilter$AuthorityEntry": "android.content.IntentFilter$AuthorityEntry",
    "JSONObject": "org.json.JSONObject",
    "JSONArray": "org.json.JSONArray",
    "JSONTokener": "org.json.JSONTokener",
    "JsonReader": "android.util.JsonReader",
    "JsonWriter": "android.util.JsonWriter",
    "JsonToken": "android.util.JsonToken",
    "DisplayMetrics": "android.util.DisplayMetrics",
    "Size": "android.util.Size",
    "SizeF": "android.util.SizeF",
    "SparseArray": "android.util.SparseArray",
    "SparseBooleanArray": "android.util.SparseBooleanArray",
    "IInterface": "android.os.IInterface",
    "SparseLongArray": "android.util.SparseLongArray",
    "MutableShort": "android.util.MutableShort",
    "MutableDouble": "android.util.MutableDouble",

    # --- ANDROID LOCATION ---
    "Address": "android.location.Address",
    "Location": "android.location.Location",
    "Criteria": "android.location.Criteria",

    # --- JAVA IO & NIO ---
    "ClassLoader": "java.lang.ClassLoader",
    "File": "java.io.File",
    "FileOutputStream": "java.io.FileOutputStream",
    "BufferedOutputStream": "java.io.BufferedOutputStream",
    "FilterInputStream": "java.io.FilterInputStream",
    "InputStream": "java.io.InputStream",
    "OutputStream": "java.io.OutputStream",
    "Reader": "java.io.Reader",
    "Writer": "java.io.Writer",
    "PrintWriter": "java.io.PrintWriter",
    "PrintStream": "java.io.PrintStream",
    "UnaryOperator": "java.util.function.UnaryOperator",
    "BufferedReader": "java.io.BufferedReader",
    "CharArrayReader": "java.io.CharArrayReader",
    "OutputStreamWriter": "java.io.OutputStreamWriter",
    "Byte": "java.lang.Byte",
    "ByteBuffer": "java.nio.ByteBuffer",
    "IntBuffer": "java.nio.IntBuffer",
    "LongBuffer": "java.nio.LongBuffer",
    "CharBuffer": "java.nio.CharBuffer",
    "Charset": "java.nio.charset.Charset",
    "charset.Charset": "java.nio.charset.Charset",
    "CharsetEncoder": "java.nio.charset.CharsetEncoder",
    "Range": "android.util.Range",
    "MatchResult": "java.util.regex.MatchResult",
    "Path": "java.nio.file.Path",
    "file.Path": "java.nio.file.Path",

    # --- JAVA NET & WEB (SERVLET) ---
    "URL": "java.net.URL",
    "URI": "java.net.URI",
    "Uri": "android.net.Uri",
    "URLConnection": "java.net.URLConnection",
    "HttpCookie": "java.net.HttpCookie",
    "Proxy": "java.net.Proxy",
    "Proxy$Type": "java.net.Proxy$Type",
    "SocketAddress": "java.net.SocketAddress",
    "PasswordAuthentication": "java.net.PasswordAuthentication",
    "HttpServletResponse": "javax.servlet.http.HttpServletResponse",
    "ServletResponse": "javax.servlet.ServletResponse",
    "ServletOutputStream": "javax.servlet.ServletOutputStream",
    "Stream": "java.util.stream.Stream",

    # --- JAVA SQL ---
    "ResultSet": "java.sql.ResultSet",
    "Array": "java.sql.Array",
    "Blob": "java.sql.Blob",
    "Clob": "java.sql.Clob",
    "NClob": "java.sql.NClob",
    "SQLXML": "java.sql.SQLXML",
    "Ref": "java.sql.Ref",
    "Date": "java.sql.Date",
    "Time": "java.sql.Time",
    "Timestamp": "java.sql.Timestamp",
    "Statement": "java.sql.Statement",
    "StackTraceElement": "java.lang.StackTraceElement",

    # --- JAVA UTIL & COLLECTIONS ---
    "List": "java.util.List",
    "ArrayList": "java.util.ArrayList",
    "Set": "java.util.Set",
    "Map": "java.util.Map",
    "Collection": "java.util.Collection",
    "Queue": "java.util.Queue",
    "Deque": "java.util.Deque",
    "Iterator": "java.util.Iterator",
    "ListIterator": "java.util.ListIterator",
    "Spliterator": "java.util.Spliterator",
    "Spliterator$OfLong": "java.util.Spliterator$OfLong",
    "Enumeration": "java.util.Enumeration",
    "Locale": "java.util.Locale",
    "Calendar": "java.util.Calendar",
    "Random": "java.util.Random",
    "StringTokenizer": "java.util.StringTokenizer",
    "Optional": "java.util.Optional",
    "OptionalInt": "java.util.OptionalInt",
    "OptionalLong": "java.util.OptionalLong",

    # --- JAVA CONCURRENT & ATOMIC ---
    "Future": "java.util.concurrent.Future",
    "TimeUnit": "java.util.concurrent.TimeUnit",
    "concurrent.TimeUnit": "java.util.concurrent.TimeUnit",
    "AtomicInteger": "java.util.concurrent.atomic.AtomicInteger",
    "AtomicReference": "java.util.concurrent.atomic.AtomicReference",

    # --- JAVA FUNCTIONAL & REGEX ---
    "BiFunction": "java.util.function.BiFunction",
    "function.UnaryOperator": "java.util.function.UnaryOperator",
    "function.Consumer": "java.util.function.Consumer",
    "function.LongConsumer": "java.util.function.LongConsumer",
    "Pattern": "java.util.regex.Pattern",
    "regex.Matcher": "java.util.regex.Matcher",

    # --- JAVA LANG & REFLECT ---
    "String": "java.lang.String",
    "StringBuilder": "java.lang.StringBuilder",
    "StringBuffer": "java.lang.StringBuffer",
    "Serializable": "java.io.Serializable",
    "Object": "java.lang.Object",
    "Integer": "java.lang.Integer",
    "Short": "java.lang.Short",
    "Double": "java.lang.Double",
    "Number": "java.lang.Number",
    "Boolean": "java.lang.Boolean",
    "CharSequence": "java.lang.CharSequence",
    "BigDecimal": "java.math.BigDecimal",
    "BigInteger": "java.math.BigInteger",
    "Class": "java.lang.Class",
    "reflect.Type": "java.lang.reflect.Type",
    "ProcessBuilder": "java.lang.ProcessBuilder",
    "Throwable": "java.lang.Throwable",
    "Exception": "java.lang.Exception",
    "ThreadGroup": "java.lang.ThreadGroup",
    "Thread": "java.lang.Thread",

    # --- OKHTTP & OKIO ---
    "MediaType": "okhttp3.MediaType",
    "Request": "okhttp3.Request",
    "Response": "okhttp3.Response",
    "ResponseBody": "okhttp3.ResponseBody",

    # --- XML (SAX & W3C) ---
    "InputSource": "org.xml.sax.InputSource",
    "NodeList": "org.w3c.dom.NodeList",
    "Node": "org.w3c.dom.Node",
}
